contentColumnType: string
fieldGroup: c49c339d-3fea-4456-a85c-416c49ada2bc # Single Fields
handle: aboutImage
instructions: ''
name: 'About Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:12ac2eea-5889-4843-bf50-e9e1063e75d0' # Blog
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:407951b9-9f17-4e1b-9319-d4dc2c5d219b' # General
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
