contentColumnType: string
fieldGroup: a6624ac9-f7c9-4cc2-a506-d2636e1e75e8 # Blog Post Field
handle: featureImage
instructions: ''
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:12ac2eea-5889-4843-bf50-e9e1063e75d0' # Blog
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:12ac2eea-5889-4843-bf50-e9e1063e75d0' # Blog
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
