contentColumnType: text
fieldGroup: 68666e72-1cb3-43ba-860f-b2bee1034eff # Global Fields
handle: siteDescription
instructions: ''
name: 'Site Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
