contentColumnType: text
fieldGroup: a6624ac9-f7c9-4cc2-a506-d2636e1e75e8 # Blog Post Field
handle: summary
instructions: 'Enter a brief, one or two sentence post summary'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
