fieldLayouts:
  8b5197ee-be15-4f10-844d-fec8474ef1ef:
    tabs:
      -
        elements:
          -
            fieldUid: e58ddb1f-42a2-4c15-81f8-cb861474c18c # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Description
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
