enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  9e1f1e8b-ff1c-4882-bd65-33e2f381b908: # Blog Tutorial
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
